version: '3'

services:
  postgres:
    image: postgres:15
    container_name: strapi_db_postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

